name: CleanHabits
description: The Minimal, Clean, Habit Tracker

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: 0.16.1
  sqflite: ^1.3.1
  settings_ui: ^0.4.0
  timeline_tile: 0.1.2
  path_provider: ^1.6.11
  charts_flutter: ^0.9.0
  heatmap_calendar: ^1.2.8
  sk_onboarding_screen: 1.0.1
  flutter_calendar_carousel: ^1.4.12
  flutter_staggered_animations: ^0.1.2
  flutter_local_notifications: ^1.4.4+3
  shared_preferences: ">=0.5.7+3 <2.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app-logo.png
    - assets/no-habit-light.png
    - assets/welcome-1.png
    - assets/welcome-2.png
    - assets/welcome-3.png
