name: CleanHabits
description: The Minimal, Clean, Habit Tracker

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: 0.16.1
  flutter_staggered_animations: ^0.1.2
  charts_flutter: ^0.9.0
  flutter_calendar_carousel: ^1.4.12
  heatmap_calendar: ^1.2.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
